APPL_COBJS += balancer.o balancer_param.o TouchSensor.o ColorSensor.o \
                GyroSensor.o SonarSensor.o Motor.o \
                Battery.o Button.o LedLight.o Sound.o \
                PIDControl.o LowPassFilter.o \
                EV3way.o \
                Section.o Stage.o Course.o 
